### ISSUE TITLE
click on p,h-diagram crashes GUI

### ISSUE THREAD

**Issue by jowr** [CoolProp/GUI#10]
```
Traceback (most recent call last):
  File "/home/jowr/.conda/envs/py3k/lib/python3.4/tkinter/__init__.py", line 1533, in __call__
    return self.func(*args)
  File "/mnt/Data/Documents/Fluids/CoolProp.GUI.git/cpgui_diagram.py", line 161, in RG1_StringVar_Callback
    self.ax.set_xlim(j2kj(Hmin),j2kj(Hmax))
NameError: name 'j2kj' is not defined
```

**Comment by mayersre** [comment]
It is fixed already, some minute ago
