### ISSUE TITLE
Saturation tables don't work

### ISSUE THREAD

**Issue by ibell** [CoolProp/GUI#18]
When I try to build default saturation table with R245fa, I get this traceback on the console:

```
[py33] C:\Users\Belli\Documents\Code\CoolProp-GUI>python cpgui.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Miniconda\envs\py33\lib\tkinter\__init__.py", line 1489, in __call__
    return self.func(*args)
  File "C:\Users\Belli\Documents\Code\CoolProp-GUI\cpgui_sattable.py", line 211, in calculate
    TLIQ,DLIQ,HLIQ,SLIQ=PropsSI(['T','D','H','S'],'P',pressures[P],'Q',0,self.ref)
  File "CoolProp.pyx", line 158, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:7363)
  File "CoolProp.pyx", line 178, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:7137)
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_ (CoolProp\CoolProp.cpp:9191)
TypeError: expected bytes, list found
```

**Comment by mayersre** [comment]
That works for me

**Comment by ibell** [comment]
Still not working for me. The exception for the table:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Miniconda\envs\py33\lib\tkinter\__init__.py", line 1489, in __call__
    return self.func(*args)
  File "C:\Users\Belli\Documents\Code\CoolProp-GUI\cpgui_sattable.py", line 211, in calculate
    TLIQ,DLIQ,HLIQ,SLIQ=PropsSI(['T','D','H','S'],'P',pressures[P],'Q',0,self.ref)
  File "CoolProp.pyx", line 158, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:7363)
  File "CoolProp.pyx", line 178, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:7137)
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_ (CoolProp\CoolProp.cpp:9191)
TypeError: expected bytes, list found
```
