### ISSUE TITLE
On py=3, Unicode error

### ISSUE THREAD

**Issue by ibell** [CoolProp/GUI#7]
I'm an idiot and ended up with an env called `py2k`, but it should really be `py3k`  In any case, looks like there is a problem.  Should this be `kg/m\xb3`?

```
[py2k] C:\Users\Belli\Documents\Code\CoolProp-GUI>python cpgui.py
Traceback (most recent call last):
  File "cpgui.py", line 199, in <module>
    CPGUI(root)
  File "cpgui.py", line 109, in __init__
    self.cpgsettings=cpg_settings(self.dialogframe0,self)
  File "C:\Users\Belli\Documents\Code\CoolProp-GUI\cpgui_settings.py", line 57, in __init__
    self.SettingsInputPanel(self.InputFrame)
  File "C:\Users\Belli\Documents\Code\CoolProp-GUI\cpgui_settings.py", line 72, in SettingsInputPanel
    I1=units[quant].index(gui_unit[quant])
ValueError: 'kg/m\xc2\xb3' is not in list
```

**Comment by mayersre** [comment]
All dependencies on De- and Encoders were removed by using pickle to write the config file. The message should no longer come up.
