### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by ibell** [CoolProp/GUI#8]
See below

```
[py33] C:\Users\Belli\Documents\Code\CoolProp-GUI>python cpgui.py
Traceback (most recent call last):
  File "C:\Miniconda\envs\py33\lib\site-packages\PIL\ImageTk.py", line 176, in paste
    tk.call("PyImagingPhoto", self.__photo, block.id)
_tkinter.TclError: invalid command name "PyImagingPhoto"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cpgui.py", line 194, in <module>
    CPGUI(root)
  File "cpgui.py", line 121, in __init__
    self.cpgNewClass=cpg_cycle1(self.dialogframe5,self)
  File "C:\Users\Belli\Documents\Code\CoolProp-GUI\cpgui_cycle1.py", line 135, in __init__
    render = ImageTk.PhotoImage(imgfile)
  File "C:\Miniconda\envs\py33\lib\site-packages\PIL\ImageTk.py", line 115, in __init__
    self.paste(image)
  File "C:\Miniconda\envs\py33\lib\site-packages\PIL\ImageTk.py", line 180, in paste
    from PIL import _imagingtk
ImportError: cannot import name _imagingtk
Fatal Python error: PyEval_RestoreThread: NULL tstate

[py33] C:\Users\Belli\Documents\Code\CoolProp-GUI>conda list
# packages in environment at C:\Miniconda\envs\py33:
#
buildingspy               1.3.0                     <pip>
coolprop                  5.0.0                     <pip>
cx-freeze                 4.3.3                     <pip>
cython                    0.22                     py33_0
dateutil                  2.1                      py33_2
glob2                     0.4.1                     <pip>
matplotlib                1.4.3                np19py33_1
nose                      1.3.4                     <pip>
numpy                     1.9.2                    py33_0
pillow                    2.7.0                    py33_0
pip                       6.0.8                    py33_0
pyparsing                 2.0.3                    py33_0
pyqt                      4.10.4                   py33_1
python                    3.3.5                         1
python-dateutil           2.4.1                    py33_0
pytz                      2015.2                   py33_0
scipy                     0.15.1               np19py33_0
setuptools                14.3                     py33_0
six                       1.9.0                    py33_0
wheel                     0.23.0                    <pip>
wxpython-phoenix          3.0.1.dev76744            <pip>
```

**Comment by mayersre** [comment]
Hi Ian,

did you compile pillow yourself?

If yes, make sure a tcl/tk dev is present. On Ubuntu I usually install 
the |tcl8.6-dev ||tk8.6-dev and
then recompile/reinstall pillow. When pillow install (with compile) is 
ready it gives a summary of
available drivers, you will find it in the install.log.
|
for Windows I use a precompiled wheel from 
http://www.lfd.uci.edu/~gohlke/pythonlibs/
If you compile on windows install the active state distribution might be 
easiest solution
http://www.activestate.com/activetcl/downloads. I do not know how 
complete the tk inside a miniconda
distribution is.

Am 31.03.2015 um 07:26 schrieb Ian Bell:

**Comment by ibell** [comment]
Nope, I was using packages installed from conda.  Perhaps I need to try
again.

**Comment by ibell** [comment]
I upgraded to pillow 2.8.0 using pip, but conda package is at 2.7.  

Now it opens fine.
